"""make_bookmaker_id_optional

Revision ID: e44de8d4f299
Revises: 7a0c7657aeed
Create Date: 2026-02-26 23:59:31.160970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44de8d4f299'
down_revision: Union[str, None] = '7a0c7657aeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'bookmaker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
